export type TemplateDefinition = {
  id: string;
  name: string;
  projectType: "dashboard" | "web-app" | "api-service" | "full-stack" | "library" | "cli-tool" | "mobile";
  framework: "react" | "nextjs" | "vite-react" | "express" | "fastify" | "hono";
  setupDepth: "recommended" | "semi-custom";
  defaultTargets: string[];
  description: string;
};

export const TEMPLATE_REGISTRY: TemplateDefinition[] = [
  {
    id: "dashboard-nextjs-recommended",
    name: "Dashboard Next.js Recommended",
    projectType: "dashboard",
    framework: "nextjs",
    setupDepth: "recommended",
    defaultTargets: ["codex", "copilot", "claude"],
    description: "Opinionated Next.js dashboard setup with shared AI workspace defaults.",
  },
  {
    id: "dashboard-vite-react-recommended",
    name: "Dashboard Vite React Recommended",
    projectType: "dashboard",
    framework: "vite-react",
    setupDepth: "recommended",
    defaultTargets: ["codex", "copilot", "claude"],
    description: "Lean Vite React internal-tool setup with dashboard-first defaults.",
  },
  {
    id: "dashboard-react-semi-custom",
    name: "Dashboard React Semi-custom",
    projectType: "dashboard",
    framework: "react",
    setupDepth: "semi-custom",
    defaultTargets: ["codex", "copilot", "claude", "mcp"],
    description: "Manual-friendly React dashboard starter with broader tool selection.",
  },
  {
    id: "web-app-nextjs-recommended",
    name: "Web App Next.js Recommended",
    projectType: "web-app",
    framework: "nextjs",
    setupDepth: "recommended",
    defaultTargets: ["codex", "copilot", "claude"],
    description: "Opinionated Next.js web app setup with shared AI workspace defaults.",
  },
  {
    id: "web-app-react-semi-custom",
    name: "Web App React Semi-custom",
    projectType: "web-app",
    framework: "react",
    setupDepth: "semi-custom",
    defaultTargets: ["codex", "copilot", "claude", "mcp"],
    description: "Manual-friendly React web app starter with broader tool selection.",
  },
  {
    id: "api-service-express-recommended",
    name: "API Service Express Recommended",
    projectType: "api-service",
    framework: "express",
    setupDepth: "recommended",
    defaultTargets: ["codex", "copilot", "claude"],
    description: "Opinionated Express API service setup with validation, testing, and auth defaults.",
  },
  {
    id: "api-service-fastify-recommended",
    name: "API Service Fastify Recommended",
    projectType: "api-service",
    framework: "fastify",
    setupDepth: "recommended",
    defaultTargets: ["codex", "copilot", "claude"],
    description: "Opinionated Fastify API service setup with schema-first validation and testing defaults.",
  },
  {
    id: "web-app-vite-react-recommended",
    name: "Web App Vite React Recommended",
    projectType: "web-app",
    framework: "vite-react",
    setupDepth: "recommended",
    defaultTargets: ["codex", "copilot", "claude"],
    description: "Lean Vite React web app setup with shared AI workspace defaults.",
  },
  {
    id: "api-service-hono-recommended",
    name: "API Service Hono Recommended",
    projectType: "api-service",
    framework: "hono",
    setupDepth: "recommended",
    defaultTargets: ["codex", "copilot", "claude"],
    description: "Edge-first Hono API service setup with validation and testing defaults.",
  },
  {
    id: "api-service-express-semi-custom",
    name: "API Service Express Semi-custom",
    projectType: "api-service",
    framework: "express",
    setupDepth: "semi-custom",
    defaultTargets: ["codex", "copilot", "claude", "mcp"],
    description: "Configurable Express API service starter with broader tool selection.",
  },
  {
    id: "api-service-fastify-semi-custom",
    name: "API Service Fastify Semi-custom",
    projectType: "api-service",
    framework: "fastify",
    setupDepth: "semi-custom",
    defaultTargets: ["codex", "copilot", "claude", "mcp"],
    description: "Configurable Fastify API service starter with broader tool selection.",
  },
  {
    id: "full-stack-nextjs-recommended",
    name: "Full-Stack Next.js Recommended",
    projectType: "full-stack",
    framework: "nextjs",
    setupDepth: "recommended",
    defaultTargets: ["codex", "copilot", "claude"],
    description: "Opinionated full-stack Next.js setup with frontend and API route defaults.",
  },
  {
    id: "full-stack-nextjs-semi-custom",
    name: "Full-Stack Next.js Semi-custom",
    projectType: "full-stack",
    framework: "nextjs",
    setupDepth: "semi-custom",
    defaultTargets: ["codex", "copilot", "claude", "mcp"],
    description: "Configurable full-stack Next.js starter with broader tool selection.",
  },
  {
    id: "library-react-recommended",
    name: "Library React Recommended",
    projectType: "library",
    framework: "react",
    setupDepth: "recommended",
    defaultTargets: ["codex", "copilot", "claude"],
    description: "Opinionated React component library setup with tsup bundling and testing defaults.",
  },
  {
    id: "library-react-semi-custom",
    name: "Library Semi-custom",
    projectType: "library",
    framework: "react",
    setupDepth: "semi-custom",
    defaultTargets: ["codex", "copilot", "claude", "mcp"],
    description: "Configurable library starter with broader tool selection.",
  },
  {
    id: "cli-tool-node-recommended",
    name: "CLI Tool Node Recommended",
    projectType: "cli-tool",
    framework: "express",
    setupDepth: "recommended",
    defaultTargets: ["codex", "copilot", "claude"],
    description: "Opinionated Node.js CLI tool setup with arg parsing and testing defaults.",
  },
  {
    id: "cli-tool-node-semi-custom",
    name: "CLI Tool Node Semi-custom",
    projectType: "cli-tool",
    framework: "express",
    setupDepth: "semi-custom",
    defaultTargets: ["codex", "copilot", "claude", "mcp"],
    description: "Configurable Node.js CLI tool starter with broader tool selection.",
  },
  {
    id: "mobile-expo-recommended",
    name: "Mobile Expo Recommended",
    projectType: "mobile",
    framework: "react",
    setupDepth: "recommended",
    defaultTargets: ["codex", "copilot", "claude"],
    description: "Opinionated Expo/React Native mobile app setup with navigation and testing defaults.",
  },
  {
    id: "mobile-expo-semi-custom",
    name: "Mobile Expo Semi-custom",
    projectType: "mobile",
    framework: "react",
    setupDepth: "semi-custom",
    defaultTargets: ["codex", "copilot", "claude", "mcp"],
    description: "Configurable Expo/React Native mobile starter with broader tool selection.",
  },
];
