import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { applyFixes } from "../../../src/doctor/fixes.js";
import type { DiagnosticFinding } from "../../../src/doctor/types.js";

const tempDirs: string[] = [];

async function makeTempDir() {
  const cwd = await mkdtemp(join(tmpdir(), "agenv-fixes-"));
  tempDirs.push(cwd);
  return cwd;
}

afterEach(async () => {
  await Promise.all(tempDirs.splice(0).map((d) => rm(d, { recursive: true, force: true })));
});

describe("applyFixes", () => {
  it("creates local override file for local_override_missing", async () => {
    const cwd = await makeTempDir();
    const findings: DiagnosticFinding[] = [
      {
        severity: "warning",
        code: "local_override_missing",
        message: "No local override file.",
        path: "ai-workspace.local.json",
        autofixable: true,
      },
    ];

    const results = await applyFixes(cwd, findings);
    expect(results.some((r) => r.code === "local_override_missing" && r.applied)).toBe(true);

    const content = await readFile(join(cwd, "ai-workspace.local.json"), "utf8");
    expect(content).toBe("{}\n");
  });

  it("skips non-fixable findings", async () => {
    const cwd = await makeTempDir();
    const findings: DiagnosticFinding[] = [
      {
        severity: "warning",
        code: "framework_mismatch",
        message: "Framework does not match.",
      },
    ];

    const results = await applyFixes(cwd, findings);
    expect(results).toHaveLength(0);
  });

  it("does not overwrite existing local override", async () => {
    const cwd = await makeTempDir();
    const existingContent = '{ "setup": { "scope": "local" } }\n';
    await writeFile(join(cwd, "ai-workspace.local.json"), existingContent, "utf8");

    const findings: DiagnosticFinding[] = [
      {
        severity: "warning",
        code: "local_override_missing",
        message: "No local override file.",
        path: "ai-workspace.local.json",
        autofixable: true,
      },
    ];

    const results = await applyFixes(cwd, findings);
    expect(results.some((r) => r.code === "local_override_missing" && !r.applied)).toBe(true);

    const content = await readFile(join(cwd, "ai-workspace.local.json"), "utf8");
    expect(content).toBe(existingContent);
  });

  it("re-applies header for ownership_modified", async () => {
    const cwd = await makeTempDir();
    const rawContent = "# My Custom Content\n\nSome body text.\n";
    await writeFile(join(cwd, "AGENTS.md"), rawContent, "utf8");

    const findings: DiagnosticFinding[] = [
      {
        severity: "warning",
        code: "ownership_modified",
        message: "Generated header missing.",
        path: "AGENTS.md",
        autofixable: true,
      },
    ];

    const results = await applyFixes(cwd, findings);
    expect(results.some((r) => r.code === "ownership_modified" && r.applied)).toBe(true);

    const content = await readFile(join(cwd, "AGENTS.md"), "utf8");
    expect(content).toContain("Generated by agenv");
  });

  it("returns applied=false when fix path missing for ownership_modified", async () => {
    const cwd = await makeTempDir();
    const findings: DiagnosticFinding[] = [
      {
        severity: "warning",
        code: "ownership_modified",
        message: "Generated header missing.",
        autofixable: true,
      },
    ];

    const results = await applyFixes(cwd, findings);
    expect(results.some((r) => r.code === "ownership_modified" && !r.applied)).toBe(true);
  });
});
