import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { checkOwnership } from "../../../src/audit/ownership.js";
import { buildRecommendedManifest } from "../../../src/manifest/defaults.js";
import { saveManifest } from "../../../src/manifest/save.js";
import { runGenerate } from "../../../src/cli/commands/generate.js";

const tempDirs: string[] = [];

async function makeTempRepo() {
  const cwd = await mkdtemp(join(tmpdir(), "agenv-ownership-"));
  tempDirs.push(cwd);
  return cwd;
}

afterEach(async () => {
  await Promise.all(tempDirs.splice(0).map((d) => rm(d, { recursive: true, force: true })));
});

describe("checkOwnership", () => {
  it("detects owned files when headers are present", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({ name: "test", framework: "react", projectType: "dashboard" });
    await saveManifest(cwd, manifest);
    await runGenerate({ cwd });

    const report = await checkOwnership(cwd, manifest);
    const owned = report.entries.filter((e) => e.status === "owned");
    expect(owned.length).toBeGreaterThan(0);
  });

  it("detects modified files when headers are removed", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({ name: "test", framework: "react", projectType: "dashboard" });
    await saveManifest(cwd, manifest);
    await runGenerate({ cwd });

    // Manually strip the generated header from AGENTS.md
    const agentsPath = join(cwd, "AGENTS.md");
    const content = await readFile(agentsPath, "utf8");
    await writeFile(agentsPath, content.replace(/^<!-- Generated by agenv.*-->\n\n/, ""), "utf8");

    const report = await checkOwnership(cwd, manifest);
    const modified = report.entries.filter((e) => e.status === "modified");
    expect(modified.some((e) => e.path === "AGENTS.md")).toBe(true);
  });

  it("detects missing generated files", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({ name: "test", framework: "react", projectType: "dashboard" });
    await saveManifest(cwd, manifest);
    // Do NOT run generate — files should be missing

    const report = await checkOwnership(cwd, manifest);
    const missing = report.entries.filter((e) => e.status === "missing");
    expect(missing.length).toBeGreaterThan(0);
  });

  it("produces findings for modified files", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({ name: "test", framework: "react", projectType: "dashboard" });
    await saveManifest(cwd, manifest);
    await runGenerate({ cwd });

    const agentsPath = join(cwd, "AGENTS.md");
    const content = await readFile(agentsPath, "utf8");
    await writeFile(agentsPath, content.replace(/^<!-- Generated by agenv.*-->\n\n/, ""), "utf8");

    const report = await checkOwnership(cwd, manifest);
    expect(report.findings.some((f) => f.code === "ownership_modified")).toBe(true);
  });

  it("produces findings for missing files", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({ name: "test", framework: "react", projectType: "dashboard" });
    await saveManifest(cwd, manifest);

    const report = await checkOwnership(cwd, manifest);
    expect(report.findings.some((f) => f.code === "ownership_missing")).toBe(true);
  });

  it("returns empty entries when no targets generate files", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({ name: "test", framework: "react", projectType: "dashboard" });
    manifest.targets.copilot = false;
    manifest.targets.claude = false;
    manifest.targets.codex = false;
    manifest.targets.mcp = false;
    await saveManifest(cwd, manifest);

    // Shared entries still apply (ai-workspace.json is always generated).
    // ai-workspace.json is on disk from saveManifest — it will be "owned".
    // Other shared files not on disk will be "missing".
    const report = await checkOwnership(cwd, manifest);
    expect(report.entries.length).toBeGreaterThan(0);
    // No "modified" findings — only "owned" or "missing"
    expect(report.findings.every((f) => f.code === "ownership_missing")).toBe(true);
    expect(report.entries.some((e) => e.status === "modified")).toBe(false);
  });
});
