import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { runAudit } from "../../src/audit/index.js";
import { buildRecommendedManifest } from "../../src/manifest/defaults.js";
import { saveManifest } from "../../src/manifest/save.js";
import { runGenerate } from "../../src/cli/commands/generate.js";
import { runInstall } from "../../src/install/apply.js";

const tempDirs: string[] = [];

async function makeTempRepo() {
  const cwd = await mkdtemp(join(tmpdir(), "agenv-audit-int-"));
  tempDirs.push(cwd);
  return cwd;
}

afterEach(async () => {
  await Promise.all(tempDirs.splice(0).map((d) => rm(d, { recursive: true, force: true })));
});

describe("audit integration", () => {
  it("returns pass on clean repo", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({ name: "test", framework: "react", projectType: "dashboard" });
    manifest.targets.mcp = false;
    await saveManifest(cwd, manifest);
    await runGenerate({ cwd });

    const result = await runAudit(cwd);
    expect(result.status).toBe("pass");
  });

  it("returns warnings for dangerous MCP presets", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({ name: "test", framework: "react", projectType: "dashboard" });
    manifest.targets.mcp = true;
    manifest.generated.mcpPresets = ["filesystem"];
    await saveManifest(cwd, manifest);
    await runGenerate({ cwd });

    const result = await runAudit(cwd);
    expect(result.findings.some((f) => f.code === "mcp_trust_dangerous")).toBe(true);
    expect(result.findings.some((f) => f.code === "mcp_dangerous_pattern")).toBe(true);
  });

  it("detects modified generated files", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({ name: "test", framework: "react", projectType: "dashboard" });
    await saveManifest(cwd, manifest);
    await runGenerate({ cwd });

    // Tamper with a generated file
    const agentsPath = join(cwd, "AGENTS.md");
    const content = await readFile(agentsPath, "utf8");
    await writeFile(agentsPath, content.replace(/^<!-- Generated by agenv.*-->\n\n/, ""), "utf8");

    const result = await runAudit(cwd);
    expect(result.ownership.entries.some((e) => e.path === "AGENTS.md" && e.status === "modified")).toBe(true);
  });

  it("detects stale lockfile", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({ name: "test", framework: "react", projectType: "dashboard" });
    manifest.packs = [{ source: "builtin", id: "secure-defaults" }];
    await saveManifest(cwd, manifest);
    await runInstall(cwd);

    // Modify manifest to make lockfile stale
    manifest.packs = [
      { source: "builtin", id: "secure-defaults" },
      { source: "builtin", id: "strict-typescript" },
    ];
    await saveManifest(cwd, manifest);

    const result = await runAudit(cwd);
    expect(result.findings.some((f) => f.code === "lockfile_stale")).toBe(true);
  });
});
