import { mkdtemp, readFile, writeFile, rm, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { runGenerate } from "../../src/cli/commands/generate.js";
import { buildRecommendedManifest } from "../../src/manifest/defaults.js";
import { saveManifest } from "../../src/manifest/save.js";

const tempDirs: string[] = [];

async function makeTempRepo(): Promise<string> {
  const cwd = await mkdtemp(join(tmpdir(), "agenv-force-"));
  tempDirs.push(cwd);
  return cwd;
}

afterEach(async () => {
  await Promise.all(tempDirs.splice(0).map((cwd) => rm(cwd, { recursive: true, force: true })));
});

describe("generate --force", () => {
  it("skips user-modified files without force", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({
      name: "test-project",
      framework: "nextjs",
    });
    await saveManifest(cwd, manifest);

    // First generate to create files
    await runGenerate({ cwd });

    // Manually modify a generated file (remove header)
    await writeFile(join(cwd, "AGENTS.md"), "# My custom agents\n", "utf8");

    // Second generate should skip the modified file
    const result = await runGenerate({ cwd });

    const summary = result.summary;
    expect("skipped" in summary && summary.skipped).toContain("AGENTS.md");
  });

  it("overwrites user-modified files with force and creates backups", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({
      name: "test-project",
      framework: "nextjs",
    });
    await saveManifest(cwd, manifest);

    // First generate
    await runGenerate({ cwd });

    // Manually modify
    await writeFile(join(cwd, "AGENTS.md"), "# My custom agents\n", "utf8");

    // Force generate should overwrite
    const result = await runGenerate({ cwd, force: true });

    const summary = result.summary;
    expect("skipped" in summary && summary.skipped).toEqual([]);
    expect("updated" in summary && summary.updated).toContain("AGENTS.md");
    expect("backedUp" in summary && summary.backedUp).toContain("AGENTS.md");

    // Check backup exists
    const backupEntries = await readdir(join(cwd, ".agenv-backups"));
    expect(backupEntries.length).toBeGreaterThan(0);

    // Check content was regenerated
    const content = await readFile(join(cwd, "AGENTS.md"), "utf8");
    expect(content).toContain("Generated by agenv");
  });
});
