import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { runGenerate } from "../../src/cli/commands/generate.js";
import { buildRecommendedManifest } from "../../src/manifest/defaults.js";
import { saveManifest } from "../../src/manifest/save.js";

const tempDirs: string[] = [];

async function makeTempRepo(): Promise<string> {
  const cwd = await mkdtemp(join(tmpdir(), "agenv-integration-"));
  tempDirs.push(cwd);
  return cwd;
}

afterEach(async () => {
  await Promise.all(tempDirs.splice(0).map((cwd) => rm(cwd, { recursive: true, force: true })));
});

describe("runGenerate", () => {
  it("writes the first base outputs end to end", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({
      name: "ops-dashboard",
      framework: "nextjs",
    });

    await saveManifest(cwd, manifest);

    const result = await runGenerate({ cwd });

    expect("created" in result.summary && result.summary.created.length).toBeGreaterThan(0);
    expect("created" in result.summary && result.summary.created).toEqual(
      expect.arrayContaining([
        "docs/ai-architecture.md",
        "docs/ai-prompts/README.md",
        "docs/ai-prompts/bootstrap.md",
        "AGENTS.md",
        ".github/copilot-instructions.md",
        ".claude/README.md",
      ]),
    );

    const agentsContent = await readFile(join(cwd, "AGENTS.md"), "utf8");
    const architectureContent = await readFile(join(cwd, "docs/ai-architecture.md"), "utf8");
    const bootstrapPromptContent = await readFile(join(cwd, "docs/ai-prompts/bootstrap.md"), "utf8");

    expect(agentsContent).toContain("Generated by agenv. Review before editing by hand.");
    expect(agentsContent).toContain("nextjs");
    expect(agentsContent).toContain("## Coding Style");
    expect(architectureContent).toContain("# AI Architecture");
    expect(architectureContent).toContain("Framework: nextjs");
    expect(bootstrapPromptContent).toContain("# Bootstrap Prompt");
    expect(bootstrapPromptContent).toContain("Ready-To-Use Prompt");
  });

  it("reports unchanged files on a second generate run", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({
      name: "ops-dashboard",
      framework: "react",
    });

    await saveManifest(cwd, manifest);
    await runGenerate({ cwd });

    const secondRun = await runGenerate({ cwd });

    expect("unchanged" in secondRun.summary && secondRun.summary.unchanged).toEqual(
      expect.arrayContaining([
        "AGENTS.md",
        "docs/ai-architecture.md",
        "docs/ai-prompts/bootstrap.md",
      ]),
    );
  });
});
