import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { parse as parseYaml } from "yaml";
import { runGenerate } from "../../src/cli/commands/generate.js";
import { buildRecommendedManifest } from "../../src/manifest/defaults.js";
import { saveManifest } from "../../src/manifest/save.js";

const tempDirs: string[] = [];

function parseFrontmatter(content: string): Record<string, unknown> {
  const end = content.indexOf("\n---\n", 4);
  return parseYaml(content.slice(4, end)) as Record<string, unknown>;
}

async function makeTempRepo(): Promise<string> {
  const cwd = await mkdtemp(join(tmpdir(), "agenv-conformance-"));
  tempDirs.push(cwd);
  return cwd;
}

afterEach(async () => {
  await Promise.all(tempDirs.splice(0).map((cwd) => rm(cwd, { recursive: true, force: true })));
});

describe("platform conformance", () => {
  it("writes discoverable, language-aware Claude, Cursor, Windsurf, Copilot, Codex, and MCP files", async () => {
    const cwd = await makeTempRepo();
    const manifest = buildRecommendedManifest({
      name: "python-service",
      framework: "fastapi",
      projectType: "api-service",
      language: "python",
      targets: {
        claude: true,
        codex: true,
        copilot: true,
        cursor: true,
        windsurf: true,
        mcp: true,
      },
      generated: {
        skills: true,
        agents: true,
        prompts: "master",
        mcpPresets: ["filesystem", "linear"],
      },
    });
    await saveManifest(cwd, manifest);
    await runGenerate({ cwd });

    const claudeInstructions = await readFile(join(cwd, ".claude", "CLAUDE.md"), "utf8");
    const claudeSkill = await readFile(
      join(cwd, ".claude", "skills", "design-api-endpoints", "SKILL.md"),
      "utf8",
    );
    const claudeAgent = await readFile(
      join(cwd, ".claude", "agents", "api-designer.md"),
      "utf8",
    );
    const cursorRule = await readFile(join(cwd, ".cursor", "rules", "coding-style.mdc"), "utf8");
    const windsurfRule = await readFile(join(cwd, ".windsurf", "rules", "coding-style.md"), "utf8");
    const claudeMcp = JSON.parse(await readFile(join(cwd, ".mcp.json"), "utf8"));
    const cursorMcp = JSON.parse(await readFile(join(cwd, ".cursor", "mcp.json"), "utf8"));
    const vscodeMcp = JSON.parse(await readFile(join(cwd, ".vscode", "mcp.json"), "utf8"));
    const codexMcp = await readFile(join(cwd, ".codex", "config.toml"), "utf8");

    expect(claudeInstructions).toContain("# python-service");
    expect(claudeInstructions).toContain("Python");
    expect(claudeInstructions).not.toContain("TypeScript");
    expect(claudeSkill).toMatch(/^---\nname: design-api-endpoints\ndescription: /);
    expect(parseFrontmatter(claudeSkill)).toMatchObject({ name: "design-api-endpoints" });
    expect(claudeSkill).toContain("\n---\n\n<!-- Generated by agenv.");
    expect(claudeAgent).toMatch(/^---\nname: api-designer\ndescription: /);
    expect(parseFrontmatter(claudeAgent)).toMatchObject({ name: "api-designer" });
    expect(parseFrontmatter(cursorRule)).toMatchObject({ globs: "**/*.py" });
    expect(parseFrontmatter(windsurfRule)).toMatchObject({
      trigger: "glob",
      globs: "**/*.py",
    });
    expect(cursorRule).toContain('globs: "**/*.py"');
    expect(windsurfRule).toMatch(/^---\ntrigger: glob\nglobs: "\*\*\/\*\.py"\n---/);
    expect(windsurfRule).toContain("\n<!-- Generated by agenv.");
    expect(cursorRule).not.toContain("TypeScript");
    expect(windsurfRule).not.toContain("TypeScript");

    expect(claudeMcp.mcpServers.filesystem).not.toHaveProperty("_trustLevel");
    expect(claudeMcp.mcpServers.linear).toEqual({
      type: "http",
      url: "https://mcp.linear.app/mcp",
    });
    expect(cursorMcp).toHaveProperty("mcpServers.filesystem");
    expect(vscodeMcp).toHaveProperty("servers.filesystem");
    expect(codexMcp).toContain('[mcp_servers."filesystem"]');
    expect(codexMcp).toContain('[mcp_servers."linear"]');
  });
});
