import type { Manifest } from "../../manifest/schema.js";
import type { GenerationPlan, PlannedFile } from "../../planner/build-plan.js";
import type { Adapter, RenderedFile, SupportResult } from "../types.js";
import {
  buildFrameworkGuidance,
  buildLanguageGuidance,
  describeLanguage,
  describeProjectType,
  sourceGlob,
} from "../project-context.js";

function supports(manifest: Manifest): SupportResult {
  return {
    supported: manifest.targets.windsurf === true,
    issues:
      manifest.targets.windsurf === true
        ? []
        : [
            {
              severity: "warning",
              code: "windsurf_target_disabled",
              message: "Windsurf output is disabled in the manifest targets.",
            },
          ],
  };
}

function plan(_manifest: Manifest, generationPlan: GenerationPlan): PlannedFile[] {
  return generationPlan.files.filter((file) => file.target === "windsurf");
}

function renderProjectContext(manifest: Manifest): string {
  const lines = [
    `---`,
    `trigger: always_on`,
    `---`,
    ``,
    `# Project Context`,
    ``,
    `This is the **${manifest.project.name}** ${manifest.project.framework} ${describeProjectType(manifest)} written in ${describeLanguage(manifest)}.`,
    ``,
    `## Key Facts`,
    ``,
    `- **Framework:** ${manifest.project.framework}`,
    `- **Project type:** ${describeProjectType(manifest)}`,
    `- **Language:** ${describeLanguage(manifest)}`,
  ];

  if (manifest.conventions.accessibility) {
    lines.push(`- **Accessibility:** required — use semantic HTML and ARIA attributes`);
  }
  if (manifest.conventions.responsive) {
    lines.push(`- **Responsive:** required — support mobile, tablet, and desktop`);
  }
  if (manifest.conventions.authModel && manifest.conventions.authModel !== "none") {
    lines.push(`- **Auth model:** ${manifest.conventions.authModel}`);
  }

  return lines.join("\n") + "\n";
}

function renderCodingStyle(manifest: Manifest): string {
  const lines = [
    `---`,
    `trigger: glob`,
    `globs: ${JSON.stringify(sourceGlob(manifest))}`,
    `---`,
    ``,
    `# Coding Style`,
    ``,
    ...buildLanguageGuidance(manifest).map((rule) => `- ${rule}`),
    ...manifest.instructions.codingStyle.map((rule) => `- ${rule}`),
  ];

  return lines.join("\n") + "\n";
}

function renderFramework(manifest: Manifest): string {
  const fw = manifest.project.framework;
  const frameworkGuidance = buildFrameworkGuidance(manifest);

  const lines = [
    `---`,
    `trigger: glob`,
    `globs: ${JSON.stringify(sourceGlob(manifest))}`,
    `---`,
    ``,
    `# ${fw.charAt(0).toUpperCase()}${fw.slice(1)} Conventions`,
    ``,
    ...frameworkGuidance.map((g) => `- ${g}`),
  ];

  return lines.join("\n") + "\n";
}

function renderCodeReview(manifest: Manifest): string {
  const lines = [
    `---`,
    `trigger: manual`,
    `---`,
    ``,
    `# Code Review Rules`,
    ``,
    ...manifest.instructions.reviewRules.map((rule) => `- ${rule}`),
  ];

  return lines.join("\n") + "\n";
}

function renderRule(file: PlannedFile, manifest: Manifest): string {
  const ruleName = file.path.split("/").pop()?.replace(".md", "") ?? "rule";
  switch (ruleName) {
    case "context":
      return renderProjectContext(manifest);
    case "coding-style":
      return renderCodingStyle(manifest);
    case "framework":
      return renderFramework(manifest);
    case "code-review":
      return renderCodeReview(manifest);
    default:
      return `# ${ruleName}\n\nGenerated by agenv for ${manifest.project.name}.\n`;
  }
}

function render(file: PlannedFile, manifest: Manifest): RenderedFile {
  return {
    path: file.path,
    trustSensitive: file.trustSensitive,
    content: renderRule(file, manifest),
  };
}

export const windsurfAdapter: Adapter = {
  id: "windsurf",
  supports,
  plan,
  render,
};
