import type { Manifest } from "../../manifest/schema.js";
import type { GenerationPlan, PlannedFile } from "../../planner/build-plan.js";
import { formatJson } from "../../utils/json.js";
import type { Adapter, RenderedFile, SupportResult } from "../types.js";

function supports(manifest: Manifest): SupportResult {
  return {
    supported: manifest.targets.claude,
    issues: manifest.targets.claude
      ? []
      : [
          {
            severity: "warning",
            code: "claude_target_disabled",
            message: "Claude output is disabled in the manifest targets.",
          },
        ],
  };
}

function plan(_manifest: Manifest, generationPlan: GenerationPlan): PlannedFile[] {
  return generationPlan.files.filter((file) => file.target === "claude");
}

function renderMarkdownForPath(file: PlannedFile, manifest: Manifest): string {
  if (file.path === ".claude/README.md") {
    const projectLabel = manifest.project.type === "web-app" ? "web app" : "dashboard";

    return `# Claude Workspace\n\nGenerated by agenv.\n\nThis workspace is configured for a ${manifest.project.framework} ${projectLabel} project.\n`;
  }

  if (file.path.includes("/skills/")) {
    const skillName = file.path.split("/").pop()?.replace(".md", "") ?? "skill";
    return `# ${skillName}\n\nGenerated skill scaffold for ${manifest.project.name}.\n`;
  }

  if (file.path.includes("/agents/")) {
    const agentName = file.path.split("/").pop()?.replace(".md", "") ?? "agent";
    return `# ${agentName}\n\nGenerated agent scaffold for ${manifest.project.name}.\n`;
  }

  return formatJson({
    generatedBy: "agenv",
    project: manifest.project.name,
  });
}

function render(file: PlannedFile, manifest: Manifest): RenderedFile {
  return {
    path: file.path,
    trustSensitive: file.trustSensitive,
    content: renderMarkdownForPath(file, manifest),
  };
}

export const claudeAdapter: Adapter = {
  id: "claude",
  supports,
  plan,
  render,
};
