import type { Manifest } from "../../manifest/schema.js";
import type { GenerationPlan, PlannedFile } from "../../planner/build-plan.js";
import type { Adapter, RenderedFile, SupportResult } from "../types.js";

function supports(manifest: Manifest): SupportResult {
  return {
    supported: manifest.targets.codex,
    issues: manifest.targets.codex
      ? []
      : [
          {
            severity: "warning",
            code: "codex_target_disabled",
            message: "Codex output is disabled in the manifest targets.",
          },
        ],
  };
}

function plan(_manifest: Manifest, generationPlan: GenerationPlan): PlannedFile[] {
  return generationPlan.files.filter((file) => file.target === "codex");
}

function render(file: PlannedFile, manifest: Manifest): RenderedFile {
  return {
    path: file.path,
    trustSensitive: file.trustSensitive,
    content: `# AGENTS\n\nGenerated by agenv.\n\n## Project\n\n- Name: ${manifest.project.name}\n- Framework: ${manifest.project.framework}\n\n## Coding Style\n\n${manifest.instructions.codingStyle.map((rule) => `- ${rule}`).join("\n")}\n\n## Review Rules\n\n${manifest.instructions.reviewRules.map((rule) => `- ${rule}`).join("\n")}\n`,
  };
}

export const codexAdapter: Adapter = {
  id: "codex",
  supports,
  plan,
  render,
};
