import type { Manifest } from "../../manifest/schema.js";
import type { GenerationPlan, PlannedFile } from "../../planner/build-plan.js";
import type { Adapter, RenderedFile, SupportResult } from "../types.js";

function supports(manifest: Manifest): SupportResult {
  return {
    supported: manifest.targets.copilot,
    issues: manifest.targets.copilot
      ? []
      : [
          {
            severity: "warning",
            code: "copilot_target_disabled",
            message: "Copilot output is disabled in the manifest targets.",
          },
        ],
  };
}

function plan(_manifest: Manifest, generationPlan: GenerationPlan): PlannedFile[] {
  return generationPlan.files.filter((file) => file.target === "copilot");
}

function render(file: PlannedFile, manifest: Manifest): RenderedFile {
  const projectLabel = manifest.project.type === "web-app" ? "web app" : "dashboard";

  return {
    path: file.path,
    trustSensitive: file.trustSensitive,
    content: `# Copilot Instructions\n\nGenerated by agenv.\n\nUse the shared ${projectLabel} conventions for ${manifest.project.name}.\n\n${manifest.instructions.codingStyle
      .map((rule) => `- ${rule}`)
      .join("\n")}\n`,
  };
}

export const copilotAdapter: Adapter = {
  id: "copilot",
  supports,
  plan,
  render,
};
