export const GENERATED_NOTICE = "Generated by agenv. Review before editing by hand.";

export function withMarkdownGeneratedHeader(content: string): string {
  return `<!-- ${GENERATED_NOTICE} -->\n\n${content}`;
}
