export const GENERATED_NOTICE = "Generated by agenv. Review before editing by hand.";

export function withMarkdownGeneratedHeader(content: string): string {
  if (content.startsWith("---\n")) {
    const frontmatterEnd = content.indexOf("\n---\n", 4);
    if (frontmatterEnd !== -1) {
      const insertionPoint = frontmatterEnd + "\n---\n".length;
      return `${content.slice(0, insertionPoint)}\n<!-- ${GENERATED_NOTICE} -->\n${content.slice(insertionPoint)}`;
    }
  }

  return `<!-- ${GENERATED_NOTICE} -->\n\n${content}`;
}

export function withLineCommentHeader(content: string): string {
  return `# ${GENERATED_NOTICE}\n\n${content}`;
}

export function canHaveGeneratedHeader(filePath: string): boolean {
  return (
    filePath.endsWith(".md") ||
    filePath.endsWith(".txt") ||
    filePath.endsWith(".env") ||
    filePath.endsWith(".example")
  );
}

export function applyGeneratedHeader(filePath: string, content: string): string {
  if (filePath.endsWith(".md")) {
    return withMarkdownGeneratedHeader(content);
  }

  if (filePath.endsWith(".env") || filePath.endsWith(".example")) {
    return withLineCommentHeader(content);
  }

  return content;
}

export function hasGeneratedHeader(filePath: string, content: string): boolean {
  if (filePath.endsWith(".md")) {
    return (
      content.startsWith(`<!-- ${GENERATED_NOTICE} -->`) ||
      (content.startsWith("---\n") && content.includes(`\n<!-- ${GENERATED_NOTICE} -->\n`))
    );
  }

  if (filePath.endsWith(".env") || filePath.endsWith(".example")) {
    return content.startsWith(`# ${GENERATED_NOTICE}`);
  }

  return false;
}
